import { useEffect,useState } from 'react'
import { Link,useLocation,useNavigate } from 'react-router-dom'
import { addDoc,collection,doc,getDocs,orderBy,query,runTransaction,serverTimestamp,where } from 'firebase/firestore'
import { createUserWithEmailAndPassword,deleteUser,signInWithEmailAndPassword,signOut } from 'firebase/auth'
import { auth,db } from './firebase/config'
import { useAuth } from './context/AuthContext'
import { Card,Empty,Loading } from './components'
const err=e=>({'auth/email-already-in-use':'Ya existe una cuenta con este correo.','auth/invalid-credential':'Correo o contraseña incorrectos.','auth/invalid-email':'Ingresa un correo electrónico válido.','auth/weak-password':'La contraseña debe tener al menos 6 caracteres.','permission-denied':'Firebase rechazó la operación. Publica las reglas de Firestore incluidas en el proyecto.','failed-precondition':'Firestore aún no está configurado o falta crear un índice requerido.'}[e.code]||'Ocurrió un error inesperado. Intenta nuevamente.')
const getConfessions=(all=false,n=0)=>getDocs(query(collection(db,'confessions'),...(all?[orderBy('createdAt','desc')]:[where('isPublic','==',true)]))).then(s=>s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,n||undefined))
export function Home(){const[items,setItems]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{getConfessions(false,3).then(setItems).catch(()=>{}).finally(()=>setLoading(false))},[]);return <><section className="hero"><div><small>✦ UN ESPACIO PARA DECIRLO</small><h1>Las palabras que el corazón no se atreve a decir.</h1><p>Comparte una confesión con la comunidad ITLA, de forma abierta o anónima.</p><Link className="button" to="/confessions/new">Escribir una confesión</Link></div><aside>♥<span>ITLA</span></aside></section><section><div className="heading"><div><small>CONFESIONES RECIENTES</small><h2>Un poquito de amor</h2></div><Link to="/confessions">Ver todas →</Link></div>{loading?<Loading/>:items.length?<div className="grid">{items.map(x=><Card key={x.id} item={x}/>)}</div>:<Empty/>}</section></>}
export function Confessions(){const{user}=useAuth(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{getConfessions(!!user).then(setItems).catch(error=>setError(err(error))).finally(()=>setLoading(false))},[user]);return <section><small>COMUNIDAD ITLA</small><h1>Confesiones</h1><p className="intro">{user?'Estás viendo las confesiones públicas y privadas.':'Inicia sesión para ver también las confesiones privadas.'}</p>{loading?<Loading/>:error?<p className="error">{error}</p>:items.length?<div className="grid">{items.map(x=><Card key={x.id} item={x}/>)}</div>:<Empty/>}</section>}
export function Login(){const[f,setF]=useState({email:'',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false),nav=useNavigate(),loc=useLocation();const submit=async e=>{e.preventDefault();if(!f.email||!f.password)return setError('Completa tu correo y contraseña.');setLoading(true);try{await signInWithEmailAndPassword(auth,f.email.trim(),f.password);nav(loc.state?.from?.pathname||'/')}catch(x){setError(err(x))}finally{setLoading(false)}};return <AuthForm title="Inicia sesión" note="¿No tienes una cuenta?" link="/register" linkText="Regístrate" error={error} onSubmit={submit}><label>Correo electrónico<input type="email" onChange={e=>setF({...f,email:e.target.value})}/></label><label>Contraseña<input type="password" onChange={e=>setF({...f,password:e.target.value})}/></label><button className="button" disabled={loading}>{loading?'Ingresando...':'Iniciar sesión'}</button></AuthForm>}
export function Register(){const[f,setF]=useState({nombre:'',apellido:'',username:'',email:'',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false),nav=useNavigate();const submit=async e=>{e.preventDefault();if(Object.values(f).some(v=>!v.trim()))return setError('Todos los campos son obligatorios.');if(!/^[a-zA-Z0-9_]{3,20}$/.test(f.username))return setError('El usuario debe tener 3 a 20 caracteres: letras, números o guion bajo.');if(f.password.length<6)return setError('La contraseña debe tener al menos 6 caracteres.');setLoading(true);let createdUser=null;try{const c=await createUserWithEmailAndPassword(auth,f.email.trim(),f.password),name=f.username.toLowerCase().trim();createdUser=c.user;await runTransaction(db,async t=>{const u=doc(db,'usernames',name);if((await t.get(u)).exists())throw Error('taken');t.set(doc(db,'users',c.user.uid),{username:name,nombre:f.nombre.trim(),apellido:f.apellido.trim(),email:f.email.trim(),createdAt:serverTimestamp()});t.set(u,{uid:c.user.uid})});nav('/')}catch(x){if(createdUser){await deleteUser(createdUser).catch(()=>{});await signOut(auth).catch(()=>{})}setError(x.message==='taken'?'El nombre de usuario ya está en uso.':err(x))}finally{setLoading(false)}};return <AuthForm title="Crea tu cuenta" note="¿Ya tienes una cuenta?" link="/login" linkText="Inicia sesión" error={error} onSubmit={submit}><div className="two"><label>Nombre<input onChange={e=>setF({...f,nombre:e.target.value})}/></label><label>Apellido<input onChange={e=>setF({...f,apellido:e.target.value})}/></label></div><label>Nombre de usuario<input placeholder="ej. maria_01" onChange={e=>setF({...f,username:e.target.value})}/></label><label>Correo electrónico<input type="email" onChange={e=>setF({...f,email:e.target.value})}/></label><label>Contraseña<input type="password" onChange={e=>setF({...f,password:e.target.value})}/></label><button className="button" disabled={loading}>{loading?'Creando cuenta...':'Crear cuenta'}</button></AuthForm>}
function AuthForm({title,note,link,linkText,error,onSubmit,children}){return <main className="center"><form className="form" onSubmit={onSubmit}><small>BIENVENIDO/A</small><h1>{title}</h1>{error&&<p className="error">{error}</p>}{children}<p className="foot">{note} <Link to={link}>{linkText}</Link></p></form></main>}
export function NewConfession(){
 const{user,profile}=useAuth();const[users,setUsers]=useState([]),[f,setF]=useState({recipientId:'',recipientName:'',body:'',anonymous:false,isPublic:true}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const nav=useNavigate();
 useEffect(()=>{getDocs(query(collection(db,'users'),orderBy('nombre'))).then(s=>setUsers(s.docs.map(d=>({id:d.id,...d.data()})))).finally(()=>setLoading(false))},[]);
 if(loading)return <Loading text="Cargando destinatarios..."/>;
 const select=e=>{const id=e.target.value,u=users.find(x=>x.id===id);setF({...f,recipientId:id==='other'?'':id,recipientName:u?`${u.nombre} ${u.apellido}`:''})};
 const submit=async e=>{e.preventDefault();if(!f.recipientName.trim()||!f.body.trim())return setError('El destinatario y la declaración son obligatorios.');if(f.body.trim().length>800)return setError('La declaración no puede superar 800 caracteres.');setSaving(true);try{await addDoc(collection(db,'confessions'),{...f,recipientId:f.recipientId||null,recipientName:f.recipientName.trim(),body:f.body.trim(),authorId:user.uid,authorUsername:profile?.username||user.email.split('@')[0],authorName:profile?`${profile.nombre} ${profile.apellido}`:'Usuario ITLA',createdAt:serverTimestamp()});nav('/confessions')}catch(error){setError(err(error))}finally{setSaving(false)}};
 return <main className="center"><form className="form wide" onSubmit={submit}><small>COMPARTE LO QUE SIENTES</small><h1>Nueva confesión</h1>{error&&<p className="error">{error}</p>}<label>¿Para quién es?<select onChange={select}><option value="">Selecciona una persona</option>{users.filter(x=>x.id!==user.uid).map(x=><option key={x.id} value={x.id}>{x.nombre} {x.apellido}</option>)}<option value="other">OTRO</option></select></label>{!f.recipientId&&<label>Nombre de tu crush<input value={f.recipientName} onChange={e=>setF({...f,recipientName:e.target.value})}/></label>}<label>Tu declaración<textarea maxLength="800" value={f.body} onChange={e=>setF({...f,body:e.target.value})}/><small>{f.body.length}/800 caracteres</small></label><Check label="Publicar como anónimo" checked={f.anonymous} set={v=>setF({...f,anonymous:v})}/><Check label="Declaración pública" checked={f.isPublic} set={v=>setF({...f,isPublic:v})}/><button className="button" disabled={saving}>{saving?'Publicando...':'Publicar confesión ♥'}</button></form></main>}
function Check({label,checked,set}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><b>{label}</b></label>}
export function Profile(){const{user,profile}=useAuth();return <main className="center"><section className="profile"><div>{profile?.nombre?.[0]||'♥'}</div><small>MI PERFIL</small><h1>{profile?.nombre} {profile?.apellido}</h1><p>@{profile?.username}</p><hr/><strong>{user?.email}</strong><p className="note">Tu contraseña se administra de forma segura en Firebase Authentication.</p></section></main>}
